[tool]
id = "health"

[[dependency]]
path = "resources/health-cli-${version.health.cli}.jar"

[[dependency]]
path = "resources/fhir-core-${version.healthcare.tool.framework}.jar"

[[dependency]]
path = "resources/commons-${version.healthcare.tool.framework}.jar"

[[dependency]]
path = "resources/fhir-to-bal-template-${version.health.cli}.jar"

[[dependency]]
path = "resources/fhir-to-bal-lib-${version.health.cli}.jar"

[[dependency]]
path = "resources/org.hl7.fhir.r4-${hapi.version}.jar"

[[dependency]]
path = "resources/ballerina-parser-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/ballerina-tools-api-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/javax.annotation-api-1.3.2.jar"

[[dependency]]
path = "resources/commons-logging-1.2.jar"

[[dependency]]
path = "resources/toml4j-0.7.2.jar"

[[dependency]]
path = "resources/hapi-fhir-structures-r4-${hapi.version}.jar"

[[dependency]]
path = "resources/maven-builder-support-3.6.3.jar"

[[dependency]]
path = "resources/shell-rt-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/central-client-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/annotations-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/javax.inject-1.jar"

[[dependency]]
path = "resources/maven-resolver-api-1.7.0.jar"

[[dependency]]
path = "resources/xpp3_xpath-1.1.4c.jar"

[[dependency]]
path = "resources/commons-lang3-3.9.jar"

[[dependency]]
path = "resources/jsr305-3.0.2.jar"

[[dependency]]
path = "resources/opentelemetry-api-1.0.0.jar"

[[dependency]]
path = "resources/maven-resolver-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/plexus-utils-3.2.1.jar"

[[dependency]]
path = "resources/asm-analysis-7.2.jar"

[[dependency]]
path = "resources/asm-tree-7.2.jar"

[[dependency]]
path = "resources/junit-4.12.jar"

[[dependency]]
path = "resources/okio-2.2.2.jar"

[[dependency]]
path = "resources/org.hl7.fhir.utilities-${hapi.version}.jar"

[[dependency]]
path = "resources/asm-7.2.jar"

[[dependency]]
path = "resources/woodstox-core-6.2.8.jar"

[[dependency]]
path = "resources/maven-resolver-provider-3.6.3.jar"

[[dependency]]
path = "resources/maven-resolver-named-locks-1.7.0.jar"

[[dependency]]
path = "resources/ucum-1.0.2.jar"

[[dependency]]
path = "resources/kotlin-stdlib-common-1.2.60.jar"

[[dependency]]
path = "resources/commons-codec-1.12.jar"

[[dependency]]
path = "resources/checker-qual-2.8.1.jar"

[[dependency]]
path = "resources/hapi-fhir-structures-dstu2-${hapi.version}.jar"

[[dependency]]
path = "resources/maven-repository-metadata-3.6.3.jar"

[[dependency]]
path = "resources/picocli-${picocli.version}.jar"

[[dependency]]
path = "resources/plexus-interpolation-1.25.jar"

[[dependency]]
path = "resources/testerina-core-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/httpclient-4.5.13.jar"

[[dependency]]
path = "resources/cava-toml-0.5.0.jar"

[[dependency]]
path = "resources/jcommander-1.72.jar"

[[dependency]]
path = "resources/slf4j-api-1.7.26.jar"

[[dependency]]
path = "resources/testerina-runtime-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/guava-28.0-jre.jar"

[[dependency]]
path = "resources/jballerina.java-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/java-semver-0.9.0.jar"

[[dependency]]
path = "resources/animal-sniffer-annotations-1.17.jar"

[[dependency]]
path = "resources/jcl-over-slf4j-1.7.28.jar"

[[dependency]]
path = "resources/netty-buffer-4.1.77.Final.jar"

[[dependency]]
path = "resources/ballerina-runtime-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/docerina-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/atomikos-util-5.0.8.jar"

[[dependency]]
path = "resources/netty-common-4.1.77.Final.jar"

[[dependency]]
path = "resources/jakarta.activation-api-1.2.2.jar"

[[dependency]]
path = "resources/bsh-2.0b6.jar"

[[dependency]]
path = "resources/antlr4-runtime-4.7.1.jar"

[[dependency]]
path = "resources/commons-compress-1.21.jar"

[[dependency]]
path = "resources/identifier-util-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/hapi-fhir-base-${hapi.version}.jar"

[[dependency]]
path = "resources/transactions-api-5.0.8.jar"

[[dependency]]
path = "resources/maven-resolver-transport-file-1.7.0.jar"

[[dependency]]
path = "resources/shell-cli-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/toml-parser-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/commons-collections-3.2.1.jar"

[[dependency]]
path = "resources/shell-core-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/maven-artifact-3.6.3.jar"

[[dependency]]
path = "resources/jline-3.11.0.jar"

[[dependency]]
path = "resources/failureaccess-1.0.1.jar"

[[dependency]]
path = "resources/asm-commons-7.2.jar"

[[dependency]]
path = "resources/maven-resolver-connector-basic-1.7.0.jar"

[[dependency]]
path = "resources/javax.transaction-api-1.3.jar"

[[dependency]]
path = "resources/commons-io-2.6.jar"

[[dependency]]
path = "resources/xpp3-1.1.4c.jar"

[[dependency]]
path = "resources/progressbar-0.7.4.jar"

[[dependency]]
path = "resources/axiom-impl-1.4.0.jar"

[[dependency]]
path = "resources/axiom-api-1.4.0.jar"

[[dependency]]
path = "resources/opentelemetry-context-1.0.0.jar"

[[dependency]]
path = "resources/testng-6.14.3.jar"

[[dependency]]
path = "resources/java-diff-utils-4.5.jar"

[[dependency]]
path = "resources/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar"

[[dependency]]
path = "resources/maven-resolver-util-1.7.0.jar"

[[dependency]]
path = "resources/maven-resolver-impl-1.7.0.jar"

[[dependency]]
path = "resources/velocity-${velocity.version}.jar"

[[dependency]]
path = "resources/maven-model-3.6.3.jar"

[[dependency]]
path = "resources/stax2-api-4.2.1.jar"

[[dependency]]
path = "resources/commons-lang-2.4.jar"

[[dependency]]
path = "resources/commons-text-1.7.jar"

[[dependency]]
path = "resources/org.eclipse.sisu.inject-0.3.4.jar"

[[dependency]]
path = "resources/ballerina-lang-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/oro-2.0.8.jar"

[[dependency]]
path = "resources/error_prone_annotations-2.3.2.jar"

[[dependency]]
path = "resources/j2objc-annotations-1.3.jar"

[[dependency]]
path = "resources/compiler-0.8.9.jar"

[[dependency]]
path = "resources/kotlin-stdlib-1.2.60.jar"

[[dependency]]
path = "resources/jansi-1.18.jar"

[[dependency]]
path = "resources/gson-2.8.9.jar"

[[dependency]]
path = "resources/annotations-13.0.jar"

[[dependency]]
path = "resources/testerina-compiler-plugin-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/maven-resolver-transport-http-1.7.0.jar"

[[dependency]]
path = "resources/transactions-jta-5.0.8.jar"

[[dependency]]
path = "resources/maven-resolver-spi-1.7.0.jar"

[[dependency]]
path = "resources/maven-model-builder-3.6.3.jar"

[[dependency]]
path = "resources/httpcore-4.4.14.jar"

[[dependency]]
path = "resources/org.jacoco.core-0.8.5.jar"

[[dependency]]
path = "resources/apache-mime4j-core-0.8.6.jar"

[[dependency]]
path = "resources/ballerina-cli-${version.ballerina.cli}.jar"

[[dependency]]
path = "resources/org.jacoco.report-0.8.5.jar"

[[dependency]]
path = "resources/transactions-5.0.8.jar"

[[dependency]]
path = "resources/okhttp-3.14.0.jar"

[[dependency]]
path = "resources/swagger-models-2.1.5.jar"

[[dependency]]
path = "resources/swagger-parser-v3-2.0.26.jar"

[[dependency]]
path = "resources/swagger-core-2.1.7.jar"

[[dependency]]
path = "resources/snakeyaml-1.27.jar"

[[dependency]]
path = "resources/jackson-dataformat-yaml-2.12.1.jar"
